In [29]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report

In [2]:
left_volume = [7000,6950,7020,6800,6780,7030,6750,7010,6790,6760]
right_volume = [7050,6900,6980,6850,6800,7000,6740,7060,6820,6770]
label = [0,0,0,1,1,0,1,0,1,1]

df = pd.DataFrame(list(zip(left_volume, right_volume,label)),columns =['Left', 'Right', 'Label'])
df

Left  Right  Label
0  7000   7050      0
1  6950   6900      0
2  7020   6980      0
3  6800   6850      1
4  6780   6800      1
5  7030   7000      0
6  6750   6740      1
7  7010   7060      0
8  6790   6820      1
9  6760   6770      1

In [34]:
df['Left'].corr(df['Label'])

-0.9787677689637657

In [35]:
df['Right'].corr(df['Label'])

-0.9004586878373203

In [20]:
X = np.array(df[['Left','Right']].values.tolist())
y = np.array(df['Label'])

In [21]:
reg = LinearRegression().fit(X, y)

In [36]:
reg.coef_

array([-0.00540212,  0.00126189])

In [37]:
reg.intercept_

29.0119431065353

In [25]:
reg.score(X,y)

0.9659770670347297

In [27]:
predictions = reg.predict(X)
classifications = predictions
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        classifications[i] = 1
    else:
        classifications[i] = 0

In [32]:
classifications

array([0., 0., 0., 1., 1., 0., 1., 0., 1., 1.])

In [39]:
y

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1], dtype=int64)

In [33]:
print(classification_report(y, classifications))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

